use_frameworks!

target 'NFBeeController_Example' do
  pod 'NFBeeController', :path => '../'

  target 'NFBeeController_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
